language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
install: true # skip travis' pre-installation of dependencies
script: ./mvnw package integration-test
deploy:
  - provider: script
    script: .travis/publish-gcs.sh
    on:
      branch: master